"""v0_2_Update_VideoData_table

Revision ID: 24b6adc64332
Revises: 65214ce03bb3
Create Date: 2024-01-22 14:45:46.933841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24b6adc64332'
down_revision: Union[str, None] = '65214ce03bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slider_img')
    op.drop_table('videodata')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videodata',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('thumbnail', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('video_link', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('video_360', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('video_720', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('video_1080', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='videodata_pkey'),
    sa.UniqueConstraint('id', name='videodata_id_key')
    )
    op.create_table('slider_img',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('img_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='slider_img_pkey'),
    sa.UniqueConstraint('id', name='slider_img_id_key')
    )
    # ### end Alembic commands ###
