"""v0_2_Update_VideoData_table

Revision ID: 65214ce03bb3
Revises: 7cb49204761d
Create Date: 2024-01-22 14:44:14.347911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65214ce03bb3'
down_revision: Union[str, None] = '7cb49204761d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'slider_img', ['id'])
    op.add_column('videodata', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('videodata', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videodata', 'updated_at')
    op.drop_column('videodata', 'created_at')
    op.drop_constraint(None, 'slider_img', type_='unique')
    # ### end Alembic commands ###
