"""update video database

Revision ID: 734fe994b8fc
Revises: ba3f8c0b03f5
Create Date: 2024-02-28 21:25:44.209494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '734fe994b8fc'
down_revision: Union[str, None] = 'ba3f8c0b03f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videodata', sa.Column('url', sa.Text(), nullable=False))
    op.add_column('videodata', sa.Column('upload_time', sa.Text(), nullable=False))
    op.add_column('videodata', sa.Column('video_time', sa.Text(), nullable=False))
    op.add_column('videodata', sa.Column('porn_star', sa.Text(), nullable=False))
    op.add_column('videodata', sa.Column('video_url', sa.Text(), nullable=False))
    op.add_column('videodata', sa.Column('main_thumb', sa.Text(), nullable=False))
    op.add_column('videodata', sa.Column('image_thumb', sa.Text(), nullable=False))
    op.alter_column('videodata', 'title',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('videodata', 'category',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_column('videodata', 'video_720')
    op.drop_column('videodata', 'video_1080')
    op.drop_column('videodata', 'description')
    op.drop_column('videodata', 'video_360')
    op.drop_column('videodata', 'thumbnail')
    op.drop_column('videodata', 'video_link')
    op.drop_column('videodata', 'slider')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videodata', sa.Column('slider', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('videodata', sa.Column('video_link', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('videodata', sa.Column('thumbnail', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('videodata', sa.Column('video_360', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('videodata', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('videodata', sa.Column('video_1080', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('videodata', sa.Column('video_720', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('videodata', 'category',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('videodata', 'title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.drop_column('videodata', 'image_thumb')
    op.drop_column('videodata', 'main_thumb')
    op.drop_column('videodata', 'video_url')
    op.drop_column('videodata', 'porn_star')
    op.drop_column('videodata', 'video_time')
    op.drop_column('videodata', 'upload_time')
    op.drop_column('videodata', 'url')
    # ### end Alembic commands ###
