"""v0_2_Update_VideoData_table

Revision ID: 7be089efd6ad
Revises: 24b6adc64332
Create Date: 2024-01-22 14:46:07.301276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7be089efd6ad'
down_revision: Union[str, None] = '24b6adc64332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
