"""v0_2_Update_VideoData_table

Revision ID: 7cb49204761d
Revises: f937cae2aa4f
Create Date: 2024-01-22 14:21:17.786143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb49204761d'
down_revision: Union[str, None] = 'f937cae2aa4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slider_img',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('img_link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('videodata', sa.Column('description', sa.String(), nullable=False))
    op.add_column('videodata', sa.Column('category', sa.String(), nullable=False))
    op.add_column('videodata', sa.Column('thumbnail', sa.Text(), nullable=False))
    op.add_column('videodata', sa.Column('video_link', sa.Text(), nullable=False))
    op.add_column('videodata', sa.Column('video_360', sa.Text(), nullable=False))
    op.add_column('videodata', sa.Column('video_720', sa.Text(), nullable=False))
    op.add_column('videodata', sa.Column('video_1080', sa.Text(), nullable=False))
    op.drop_column('videodata', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videodata', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('videodata', 'video_1080')
    op.drop_column('videodata', 'video_720')
    op.drop_column('videodata', 'video_360')
    op.drop_column('videodata', 'video_link')
    op.drop_column('videodata', 'thumbnail')
    op.drop_column('videodata', 'category')
    op.drop_column('videodata', 'description')
    op.drop_table('slider_img')
    # ### end Alembic commands ###
