"""v0_1_Create_VideoData_table

Revision ID: a14d1dce8a1d
Revises: db1a7145be06
Create Date: 2024-01-22 14:04:29.969062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a14d1dce8a1d'
down_revision: Union[str, None] = 'db1a7145be06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
