"""v0_1_Create_VideoData_table

Revision ID: f937cae2aa4f
Revises: 69da3cfca4af
Create Date: 2024-01-22 14:10:10.942091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f937cae2aa4f'
down_revision: Union[str, None] = '69da3cfca4af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'videodata', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videodata', type_='unique')
    # ### end Alembic commands ###
